server:
  port: 5000
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms
    password: Festo4.0
    username: Festo
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      enabled: true

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: assign_id


logging:
  level:
    root: debug
